# Generated by Django 5.2.6 on 2026-09-16 09:12

import cloudinary_storage.storage
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import virtuallab.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionBank', '0032_remove_apparatusitem_experiment_delete_dbstoredimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'QuestionBank_programme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DBStoredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'QuestionBank_dbstoredimage',
            },
        ),
        migrations.CreateModel(
            name='ExperimentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Question Text')),
                ('marks', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'QuestionBank_experimentquestion',
            },
        ),
        migrations.CreateModel(
            name='VirtualExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('objective', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Objective')),
                ('theory', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Theory')),
                ('method_summary', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Method Summary')),
                ('recording_guide_tables', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Create or paste reference tables and guidelines for students here.', null=True, verbose_name='Data Recording Guide')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('year_group', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], help_text='Select the year group this experiment is for', max_length=10)),
                ('unlock_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When this experiment becomes available')),
                ('lock_time', models.DateTimeField(blank=True, help_text='Deadline after which reports can no longer be submitted', null=True)),
                ('requires_report', models.BooleanField(default=True)),
                ('requires_questions', models.BooleanField(default=False)),
                ('needs_graph', models.BooleanField(default=False, help_text='Check if this experiment requires a graph editor')),
            ],
            options={
                'db_table': 'QuestionBank_virtualexperiment',
                'verbose_name': 'Virtual Experiment',
                'verbose_name_plural': 'Virtual Experiments',
            },
        ),
        migrations.CreateModel(
            name='YearReports',
            fields=[
            ],
            options={
                'verbose_name': 'Experiment Reports by Year',
                'verbose_name_plural': 'Experiment Reports by Year',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QuestionBank.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeReports',
            fields=[
            ],
            options={
                'verbose_name': 'Experiment Report by Programme',
                'verbose_name_plural': 'Experiment Reports by Programme',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('virtuallab.programme',),
        ),
        migrations.CreateModel(
            name='ExperimentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('data_analysis', models.TextField(blank=True, help_text='Saved LaTeX from MathQuill lines', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='draft_uploads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_experimentdraft',
                'ordering': ['-last_updated'],
                'unique_together': {('experiment', 'student', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_members', models.TextField(blank=True, help_text='List of group members who participated', null=True, verbose_name='Group Members')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='Objective/Aim')),
                ('theory', models.TextField(blank=True, null=True, verbose_name='Theory/Introduction')),
                ('apparatus_scope', models.TextField(blank=True, null=True, verbose_name='Apparatus/Scope')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='Procedure/Method')),
                ('results', models.TextField(blank=True, null=True, verbose_name='Results/Raw Data')),
                ('data_analysis', models.TextField(blank=True, null=True, verbose_name='Data & Error Analysis')),
                ('discussion', models.TextField(blank=True, null=True, verbose_name='Discussion')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('references', models.TextField(blank=True, null=True, verbose_name='References')),
                ('observation', models.TextField(verbose_name='Observation')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data Collected')),
                ('is_preliminary_submitted', models.BooleanField(default=False)),
                ('preliminary_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='experiment_reports/', verbose_name='Attach Final Report')),
                ('graph_x_values', models.TextField(blank=True, help_text='Comma-separated list of X values (e.g., 1, 2, 3, 4)', null=True, verbose_name='X-Axis Values')),
                ('graph_y_values', models.TextField(blank=True, help_text='Comma-separated list of Y values (e.g., 10, 20, 30, 40)', null=True, verbose_name='Y-Axis Values')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('draft_used', models.OneToOneField(blank=True, help_text='Draft that was used to submit this report, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_report', to='virtuallab.experimentdraft')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_experimentreport',
            },
        ),
        migrations.CreateModel(
            name='ExperimentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_json', models.JSONField(blank=True, default=list, help_text="List of points in the form [{'x': 1, 'y': 2}, ...]")),
                ('vector_json', models.JSONField(blank=True, help_text='Full Konva stage JSON including freehand drawings', null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('x_label', models.CharField(blank=True, max_length=100, null=True)),
                ('y_label', models.CharField(blank=True, max_length=100, null=True)),
                ('image_snapshot', models.ImageField(blank=True, help_text='Optional image snapshot of the graph for preview or AI evaluation.', null=True, upload_to='graph_snapshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='The lab report this graph belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='virtuallab.experimentreport')),
            ],
            options={
                'db_table': 'QuestionBank_experimentgraph',
            },
        ),
        migrations.CreateModel(
            name='ExperimentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtuallab.experimentquestion')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='virtuallab.experimentreport')),
            ],
            options={
                'db_table': 'QuestionBank_experimentanswer',
            },
        ),
        migrations.CreateModel(
            name='ReportEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='virtuallab.experimentreport')),
            ],
            options={
                'db_table': 'QuestionBank_reportevaluation',
            },
        ),
        migrations.CreateModel(
            name='TheoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='theory_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_images', to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_theoryimage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Instruction')),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='step_images/')),
                ('video', models.FileField(blank=True, null=True, storage=virtuallab.storage_backends.VideoCloudinaryStorage(), upload_to='step_videos/')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or Google Drive video link (optional)', null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_experimentstep',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='experimentquestion',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='virtuallab.virtualexperiment'),
        ),
        migrations.CreateModel(
            name='ExpectedExperimentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Expected graph title', max_length=255)),
                ('x_quantity', models.CharField(help_text='Expected X-axis quantity', max_length=100)),
                ('y_quantity', models.CharField(help_text='Expected Y-axis quantity', max_length=100)),
                ('expected_slope', models.FloatField(blank=True, help_text='Expected gradient of the graph', null=True)),
                ('slope_tolerance', models.FloatField(default=0.2, help_text='Allowed fractional deviation (e.g. 0.2 = ±20%)')),
                ('x_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('y_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_trend', models.CharField(choices=[('linear', 'Linear'), ('inverse', 'Inverse'), ('quadratic', 'Quadratic'), ('constant', 'Constant'), ('unknown', 'Unknown')], default='linear', max_length=50)),
                ('min_points', models.PositiveIntegerField(default=5)),
                ('mandatory', models.BooleanField(default=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_graphs', to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_expectedexperimentgraph',
            },
        ),
        migrations.CreateModel(
            name='ExpectedDataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(help_text='e.g. Copper cylinder', max_length=120)),
                ('quantity', models.CharField(help_text='e.g. density, volume, reading error', max_length=120)),
                ('formula_latex', models.TextField(help_text='Enter the formula in LaTeX format, e.g. V = (4/3)πr^3')),
                ('alt_formula_latex', models.TextField(blank=True, help_text='Optional alternate formula in LaTeX, e.g. V ≈ 1.333 r^3', null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_data_analysis', to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_expecteddataanalysis',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApparatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='apparatus_items/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparatus_items', to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_apparatusitem',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeExperiment',
            fields=[
            ],
            options={
                'verbose_name': 'Experiment Group',
                'verbose_name_plural': 'Experiment Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('virtuallab.virtualexperiment',),
        ),
        migrations.CreateModel(
            name='ExpectedMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(help_text='e.g. Copper cylinder', max_length=120)),
                ('quantity', models.CharField(help_text='e.g. diameter', max_length=60)),
                ('instrument', models.CharField(default='__any__', max_length=60)),
                ('expected_value', models.CharField(blank=True, max_length=120, null=True)),
                ('expected_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('tolerance', models.CharField(blank=True, help_text='±5 % or ±0.2 mm', max_length=20)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_measurements', to='virtuallab.virtualexperiment')),
            ],
            options={
                'db_table': 'QuestionBank_expectedmeasurement',
                'ordering': ['order', 'id'],
                'unique_together': {('experiment', 'object_name', 'quantity', 'instrument')},
            },
        ),
    ]